# Generated by Django 5.1.4 on 2025-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_student_delete_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="used_storage",
            field=models.BigIntegerField(
                default=0, help_text="Total storage used by the user in bytes."
            ),
        ),
    ]
