# Generated by Django 5.1.4 on 2025-02-15 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_url", models.URLField()),
                ("transcript", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lines", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddedTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("embed_code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Essay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("conditions", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FillInTheBlanks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Fill In The Blanks", max_length=255),
                ),
                ("text", models.TextField()),
                (
                    "display_format",
                    models.CharField(
                        choices=[
                            ("with_list", "With list"),
                            ("without_list", "Without list"),
                        ],
                        default="with_list",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(unique=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MakeASentence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Make A Sentence", max_length=255)),
                ("sentences", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="MatchUpTheWords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Match Up The Words", max_length=255),
                ),
                ("pairs", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Note", max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SortIntoColumns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Sort Into Columns", max_length=255),
                ),
                ("columns", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("questions", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="TrueOrFalse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statements", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Unscramble",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Unscramble", max_length=255)),
                ("words", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Word List", max_length=255)),
                ("words", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "student_level",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("elementary", "Elementary"),
                            ("pre_intermediate", "Pre-Intermediate"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper-Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelImageOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_order", models.PositiveIntegerField()),
                (
                    "image_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.imageusage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelImages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("labels", models.JSONField()),
                (
                    "image_urls",
                    models.ManyToManyField(
                        related_name="label_images",
                        through="hub.LabelImageOrder",
                        to="hub.imageusage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labelimageorder",
            name="label_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hub.labelimages"
            ),
        ),
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("lexical_topics", models.TextField(blank=True, null=True)),
                ("grammar_topics", models.TextField(blank=True, null=True)),
                ("extra_topics", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="hub.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hub.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BaseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_tasks",
                        to="hub.section",
                    ),
                ),
            ],
        ),
    ]
