# Generated by Django 5.1.4 on 2025-02-16 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["student", "teacher"]},
                        related_name="active_classrooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Активные ученики",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="hub.lesson",
                        verbose_name="Текущий урок",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        limit_choices_to={"role__in": ["student", "teacher"]},
                        related_name="classrooms_as_student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученики",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        limit_choices_to={"role": "teacher"},
                        related_name="classrooms_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учителя",
                    ),
                ),
                (
                    "temporary_students",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "student"},
                        related_name="temporary_classrooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Временные ученики",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_records",
                        to="hub.classroom",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_lessons",
                        to="hub.lesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "lesson")},
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="completed_lessons",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_classrooms",
                through="hub.CompletedLesson",
                to="hub.lesson",
                verbose_name="Пройденные уроки",
            ),
        ),
        migrations.CreateModel(
            name="TemporaryStudentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_access_records",
                        to="hub.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_classroom_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
