# Generated by Django 5.1.4 on 2025-02-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_alter_classroom_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="name",
            field=models.CharField(default="Class", max_length=255),
        ),
    ]
