# Generated by Django 5.1.4 on 2025-02-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_useranswer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("classroom", "task")},
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
    ]
