# Generated by Django 5.1.4 on 2025-02-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_alter_useranswer_unique_together_useranswer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
