# Generated by Django 5.1.4 on 2025-03-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_useranswer_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="topic",
        ),
    ]
