# Generated by Django 5.1.4 on 2025-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_remove_section_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
