# Generated by Django 5.1.4 on 2025-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0011_lesson_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="title",
            field=models.CharField(default="Аудио", max_length=255),
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(default="Изображение", max_length=255),
        ),
        migrations.AddField(
            model_name="labelimages",
            name="title",
            field=models.CharField(default="Подпишите картинку", max_length=255),
        ),
        migrations.AddField(
            model_name="test",
            name="title",
            field=models.CharField(default="Тест", max_length=255),
        ),
        migrations.AddField(
            model_name="trueorfalse",
            name="title",
            field=models.CharField(default="Правда или ложь", max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="Статья", max_length=255),
        ),
        migrations.AlterField(
            model_name="embeddedtask",
            name="title",
            field=models.CharField(
                default="Выполните интерактивное задание", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="fillintheblanks",
            name="title",
            field=models.CharField(default="Заполните пропуски", max_length=255),
        ),
        migrations.AlterField(
            model_name="makeasentence",
            name="title",
            field=models.CharField(default="Составьте предложения", max_length=255),
        ),
        migrations.AlterField(
            model_name="matchupthewords",
            name="title",
            field=models.CharField(
                default="Соотнесите слова с переводами", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(default="Заметка", max_length=255),
        ),
        migrations.AlterField(
            model_name="sortintocolumns",
            name="title",
            field=models.CharField(default="Распределите по колонкам", max_length=255),
        ),
        migrations.AlterField(
            model_name="unscramble",
            name="title",
            field=models.CharField(default="Составьте слова из букв", max_length=255),
        ),
        migrations.AlterField(
            model_name="wordlist",
            name="title",
            field=models.CharField(default="Список слов", max_length=255),
        ),
    ]
