# Generated by Django 5.1.4 on 2025-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0013_alter_fillintheblanks_display_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labelimageorder",
            name="image_usage",
        ),
        migrations.RemoveField(
            model_name="labelimages",
            name="image_urls",
        ),
        migrations.RemoveField(
            model_name="labelimageorder",
            name="label_image",
        ),
        migrations.RemoveField(
            model_name="image",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="labelimages",
            name="labels",
        ),
        migrations.AddField(
            model_name="labelimages",
            name="images",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ImageUsage",
        ),
        migrations.DeleteModel(
            name="LabelImageOrder",
        ),
    ]
