# Generated by Django 5.1.4 on 2025-04-05 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_remove_labelimageorder_image_usage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(unique=True)),
                ("image_hash", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
