# Generated by Django 5.1.4 on 2025-04-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0015_imageusage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageUsage",
        ),
    ]
