# Generated by Django 5.1.4 on 2025-04-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0016_delete_imageusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetask",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_tasks",
                to="hub.section",
            ),
        ),
    ]
