# Generated by Django 5.1.4 on 2025-04-06 07:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0017_alter_basetask_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name="basetask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basetask",
            name="size",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="basetask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
