# Generated by Django 5.1.4 on 2025-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0018_imageusage_basetask_created_at_basetask_size_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageUsage",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="score",
        ),
        migrations.AddField(
            model_name="useranswer",
            name="correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="incorrect_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="max_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="audio",
            name="title",
            field=models.CharField(default="Прослушай аудио", max_length=255),
        ),
    ]
