# Generated by Django 5.1.4 on 2025-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_delete_imageusage_remove_useranswer_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="answer_data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="max_score",
            field=models.IntegerField(default=10),
        ),
    ]
