# Generated by Django 5.1.4 on 2025-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_alter_useranswer_answer_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="features",
            field=models.JSONField(default={"copying": True}),
        ),
    ]
