# Generated by Django 5.1.4 on 2025-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0021_classroom_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
